### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Renna42** [Harry-zklcdc/MCDR-Plugins#1]
1. 请问你知道PLUGIN_METADATA的author是可以为一个列表的吗
2. 为什么不贴个插件原链接呢
3. "私发玩家死亡坐标 (需要 MinecraftDataAPI and MoreAPIs)" 中的MoreAPIs应当指向https://github.com/Harry-zklcdc/MCDR-Plugins/tree/main/MoreAPIs

**Comment by Harry-zklcdc** [comment]
明天修改
如有侵权，请告知我删除
（PS：真不知道author可以是列表（捂脸））

**Comment by Harry-zklcdc** [comment]
修改后我再回复一下这个issue，征求一下您的意见

**Comment by Renna42** [comment]
不看文档，反手拍死:-)

**Comment by Harry-zklcdc** [comment]
> 不看文档，反手拍死:-)

没看那部分，去看了事件注册那一块（捂脸）

**Comment by HuajiMUR233** [comment]
顺便问下改了我插件哪些地方
(因为我把仓库重新开了:) )

**Comment by Harry-zklcdc** [comment]
第一次发布修改的开源插件，如有错误，请多多指正

**Comment by Harry-zklcdc** [comment]
已修改，请您检查一下是否符合规范
